### PR TITLE
[BTFS-1437] - Generate js file dep of gogo_pb.js for offline sign

### PR DESCRIPTION
**Pull request by uchetron**
- gogo_pb.js for offline sign

### CODE REVIEW

**Comment by uchetron** [comment]
@wxue added a line to generate dependency for offline sign

**Review by wxue — COMMENTED** [review]
If I pick up the context correctly -- this is not only for offline sign, but to generate js version of all dependencies right?

**Comment by uchetron** [comment]
@wxue  Every js file that I have generated from .protos in go-btfs-common requires gogo_pb.js (see below js line), which is why I need this file to be generated, too.
var github_com_tron$us_protobuf_gogoproto_gogo_pb = require('../gogo_pb.js');
I have made a change to the path that protoc search for files to convert to js.

**Review by wxue — DISMISSED** [review]
lgtm (Can you use your local branch to ```make install``` this, and double check it in go-btfs-common before merge in?)

**Comment by uchetron** [comment]
@wxue okay, did a 'make' in \gogoproto , and it produced the js file. Used the file in my repo and it worked.

**Review by wxue — APPROVED** [review]

**Pull request merged**
